import os

env = Environment(CCFLAGS = '-std=c++11 -g -Wall -Werror',
        CPPDEFINES=['__GXX_EXPERIMENTAL_CXX0X__', 'GLEW_STATIC'],
        CPPPATH = ['.', '../depend/openmassive/src'],
        LIBPATH = ['../depend/openmassive/build'])

# Load environment variables
env.Replace(**os.environ)

# Source section
sources = Split("""
Main.cpp
game/Block.cpp
game/Game.cpp
game/GameState.cpp
game/Pad.cpp
game/PadController.cpp
game/StateStack.cpp
graphics/Renderer.cpp
""")

# Object section
objects = env.Object(source = sources)

# Target section
binary = env.Program(
        target = 'falksalt',
        source = objects,
        LIBS = ['sfml-system', 'sfml-window',
            'sfml-graphics',
            'om-util'])

all_targets = [binary]


# Aliases
env.Alias('all', all_targets)

Default(all_targets)

